[package]
name = "time_tracker"
version = "0.1.0"
edition = "2021"
authors = ["Time Tracker Team"]
description = "一个现代化的时间跟踪和管理工具"
license = "MIT"
repository = "https://github.com/user/time_tracker"
readme = "README.md"
keywords = ["time", "tracker", "productivity", "rust", "gui"]
categories = ["command-line-utilities", "gui"]

# 打包元数据
[package.metadata]
# Windows 特定配置
[package.metadata.winres]
OriginalFilename = "time_tracker.exe"
LegalCopyright = "Copyright (c) 2025 Time Tracker Team"
ProductName = "TimeTracker"
FileDescription = "现代化时间跟踪工具"

# 应用图标和资源
[package.metadata.bundle]
name = "TimeTracker"
identifier = "com.timetracker.app"
icon = ["assets/icon.png"]
version = "0.1.0"
copyright = "Copyright (c) 2025 Time Tracker Team"
category = "Productivity"
short_description = "现代化的时间跟踪和管理工具"
long_description = """
TimeTracker 是一个功能强大的时间跟踪和管理工具，
帮助您提高工作效率，更好地管理时间。
支持任务分类、统计报告、数据导入导出等功能。
"""

# macOS 特定配置
[package.metadata.bundle.osx]
minimum_system_version = "10.11"
frameworks = []

# Windows 特定配置  
[package.metadata.bundle.windows]
wix_language = "zh-CN"

# Linux 特定配置
[package.metadata.bundle.linux]
depends = []

[dependencies]
# CLI 依赖
clap = { version = "4.0", features = ["derive", "color"] }
colored = "2.0"

# 数据库
rusqlite = { version = "0.29", features = ["bundled", "backup"] }

# 序列化
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
csv = "1.3"

# 时间处理  
chrono = { version = "0.4", features = ["serde"] }

# UUID
uuid = { version = "1.0", features = ["v4", "serde"] }

# 日志
log = "0.4"
env_logger = "0.10"

# 错误处理
anyhow = "1.0"
thiserror = "1.0"

# 异步
tokio = { version = "1.0", features = ["full"] }

# 系统目录
dirs = "5.0"

# GUI (可选)
eframe = { version = "0.28", optional = true }
egui = { version = "0.28", optional = true }

# 正则表达式
regex = "1.0"

# 随机数
rand = "0.8"

[dev-dependencies]
tempfile = "3.0"

# 打包工具
[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[build-dependencies]
# 跨平台打包工具（可选）

[features]
default = ["gui"]
gui = ["eframe", "egui"]
cli-only = []

[[bin]]
name = "time_tracker"
path = "src/main.rs"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

[profile.dev]
opt-level = 0
debug = true
